[project]
name = "ObjectMeasurer"     # pip install BodySegmentPainter
version = "0.1.1"
description = "Segment and color OpenCV contours"
requires-python = ">=3.9"
dependencies = [
  "numpy>=1.22",
  "opencv-python>=4.7",
  "OpenCVContourSVGConverter @ git+https://github.com/justingeeslin/convert-opencv-contour-svg.git"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
python_files = ["Test*.py", "test_*.py"]
